"""empty message

Revision ID: 80f449c6aa75
Revises: fa68dd647caa
Create Date: 2021-12-02 08:00:55.223790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f449c6aa75'
down_revision = 'fa68dd647caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('recipe', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('recipe', sa.Column('num_of_servings', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('cook_time', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('directions', sa.String(length=1000), nullable=True))
    op.add_column('recipe', sa.Column('is_publish', sa.Boolean(), nullable=True))
    op.drop_constraint('recipe_email_key', 'recipe', type_='unique')
    op.drop_constraint('recipe_username_key', 'recipe', type_='unique')
    op.drop_column('recipe', 'is_active')
    op.drop_column('recipe', 'email')
    op.drop_column('recipe', 'username')
    op.drop_column('recipe', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('recipe_username_key', 'recipe', ['username'])
    op.create_unique_constraint('recipe_email_key', 'recipe', ['email'])
    op.drop_column('recipe', 'is_publish')
    op.drop_column('recipe', 'directions')
    op.drop_column('recipe', 'cook_time')
    op.drop_column('recipe', 'num_of_servings')
    op.drop_column('recipe', 'description')
    op.drop_column('recipe', 'name')
    # ### end Alembic commands ###
